package co.edu.uniquindio.poo.ProyectoFinal2025_2.Util.UtilService;

import java.util.UUID;

/**
 * Utility class for generating unique identifiers across the application.
 *
 * <p>This utility centralizes all ID generation logic, ensuring consistency and making it easy
 * to modify ID generation strategies in the future if needed (e.g., switching to sequential IDs,
 * custom formats, or external ID generation services).</p>
 *
 * <p><b>ID Generation Strategies:</b></p>
 * <ul>
 *     <li><b>Generic IDs:</b> {@link #generateId()} - Uses UUID for universally unique identifiers</li>
 *     <li><b>Invoice Numbers:</b> {@link #generateInvoiceNumber()} - Time-based invoice numbering</li>
 * </ul>
 *
 * <p><b>Usage Examples:</b></p>
 * <pre>
 * // In Services:
 * String userId = IdGenerationUtil.generateId();
 * String invoiceNum = IdGenerationUtil.generateInvoiceNumber();
 *
 * // In Controllers:
 * PersonCreationData data = new PersonCreationData.Builder()
 *         .withId(IdGenerationUtil.generateId())
 *         // ...
 *         .build();
 * </pre>
 *
 * <p><b>Benefits of Centralization:</b></p>
 * <ul>
 *     <li>Single point of modification for ID generation logic</li>
 *     <li>Consistent ID formats across all entities</li>
 *     <li>Easy to add custom prefixes or validation</li>
 *     <li>Facilitates future migration to alternative ID strategies</li>
 * </ul>
 *
 * @author Sistema de Gestión de Envíos
 * @version 1.0
 * @since 2025
 * @see java.util.UUID
 */
public final class IdGenerationUtil {

    // =================================================================================================================
    // CONSTRUCTOR
    // =================================================================================================================

    /**
     * Private constructor to prevent instantiation.
     * This is a utility class with only static methods.
     *
     * @throws UnsupportedOperationException if instantiation is attempted
     */
    private IdGenerationUtil() {
        throw new UnsupportedOperationException("Utility class cannot be instantiated");
    }

    // =================================================================================================================
    // GENERIC ID GENERATION
    // =================================================================================================================

    /**
     * Generates a universally unique identifier (UUID) as a string.
     *
     * <p>This method uses Java's {@link UUID#randomUUID()} to generate a version 4 (random) UUID.
     * UUIDs generated by this method have extremely low collision probability and are suitable
     * for use as primary keys in distributed systems.</p>
     *
     * <p><b>UUID Format:</b> {@code 550e8400-e29b-41d4-a716-446655440000}</p>
     *
     * <p><b>Use Cases:</b></p>
     * <ul>
     *     <li>User IDs</li>
     *     <li>Order IDs</li>
     *     <li>Shipment IDs</li>
     *     <li>Payment IDs</li>
     *     <li>Any entity requiring a unique identifier</li>
     * </ul>
     *
     * @return A unique identifier string in UUID format
     *
     * @see UUID#randomUUID()
     */
    public static String generateId() {
        return UUID.randomUUID().toString();
    }

    // =================================================================================================================
    // SPECIALIZED ID GENERATION
    // =================================================================================================================

    /**
     * Generates a unique invoice number with a timestamp-based format.
     *
     * <p>This method creates invoice numbers in the format: {@code INV-<timestamp>}
     * where timestamp is the current time in milliseconds since epoch.</p>
     *
     * <p><b>Invoice Number Format:</b> {@code INV-1640995200000}</p>
     *
     * <p><b>Characteristics:</b></p>
     * <ul>
     *     <li>Human-readable prefix: "INV-"</li>
     *     <li>Chronologically sortable (timestamp-based)</li>
     *     <li>Unique within the same millisecond</li>
     *     <li>Can be easily parsed to extract creation time</li>
     * </ul>
     *
     * <p><b>Note:</b> If you need multiple invoices within the same millisecond,
     * consider adding a sequential counter or combining with {@link #generateId()}.</p>
     *
     * @return A unique invoice number string in the format "INV-<timestamp>"
     *
     * @see System#currentTimeMillis()
     */
    public static String generateInvoiceNumber() {
        return "INV-" + System.currentTimeMillis();
    }

}
