package co.edu.uniquindio.poo.proyectofiinal2025_2.Model;

import lombok.*;

import java.util.UUID;

/**
 * Represents a physical address with an optional alias (e.g., "Home" or "Office").
 * <p>
 * Contains details such as street, city, state, country, and postal code.
 * The equals() and hashCode() methods are automatically generated by Lombok,
 * and consider all fields by default. Use the alias primarily for user-friendly labeling.
 * </p>
 */

@Setter
@Getter
@ToString
@Builder

public class Address {

    private String id;       // Unique identifier for the address
    private String alias;    // User-friendly name for the address (e.g., Home, Office)
    private String street;   // Street name and number
    private String city;     // City of the address
    private String state;    // State or province
    private String country;  // Country
    private String zipCode;  // Postal code

}
