package co.edu.uniquindio.poo.proyectofiinal2025_2.Model;

import java.time.LocalDateTime;

/**
 * Represents an order made by a user.
 * Each order is linked to one user, generates one shipment,
 * and is associated with one payment.
 */
public class Order {

    private String id;                  // Unique order identifier
    private User user;                  // User who created the order
    private Shipment shipment;          // Shipment associated with the order
    private Payment payment;            // Payment for this order
    private LocalDateTime createdAt;    // Date and time when the order was created
    private String status;              // e.g. "Pending", "In Progress", "Delivered", "Cancelled"

    /**
     * Constructs a new Order.
     *
     * @param id        unique identifier
     * @param user      user who created the order
     * @param shipment  shipment generated by the order
     * @param payment   payment for the order
     * @param createdAt timestamp when the order was created
     * @param status    current status of the order
     */
    public Order(String id, User user, Shipment shipment, Payment payment, LocalDateTime createdAt, String status) {
        this.id = id;
        this.user = user;
        this.shipment = shipment;
        this.payment = payment;
        this.createdAt = createdAt;
        this.status = status;
    }

    // ======================
    // Getters
    // ======================

    public String getId() {
        return id;
    }

    public User getUser() {
        return user;
    }

    public Shipment getShipment() {
        return shipment;
    }

    public Payment getPayment() {
        return payment;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public String getStatus() {
        return status;
    }

    // ======================
    // Setters
    // ======================

    public void setId(String id) {
        this.id = id;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public void setShipment(Shipment shipment) {
        this.shipment = shipment;
    }

    public void setPayment(Payment payment) {
        this.payment = payment;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    // ======================
    // ToString
    // ======================

    @Override
    public String toString() {
        return "Order{" +
                "id='" + id + '\'' +
                ", user=" + (user != null ? user.getName() + " " + user.getLastName() : "null") +
                ", shipment=" + (shipment != null ? shipment.getId() : "null") +
                ", payment=" + (payment != null ? payment.getAmount() + " via " + payment.getPaymentMethod().getType() : "null") +
                ", createdAt=" + createdAt +
                ", status='" + status + '\'' +
                '}';
    }
}
